[package]
name = "cobble"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
colorsys = "0.6.6"
image = "0.24.5"
lab = "0.11.0"
noise = "0.8.2"
rand = "0.8.5"
