program     = *statement

statement   = [IDENT "="] pipeline

pipeline    = [pipeline "->"] base-expr

base-expr   = IDENT [args]
base-expr  =/ NUMBER / SYMBOL
base-expr  =/ args

args        = "(" [statement *("," statement) [","]] ")"

IDENT       = /[a-z][a-zA-Z0-9_']*/
NUMBER      = /[+\-]?[0-9][0-9_']*(\.[0-9][0-9_']*)?([eE][+\-]?[0-9][0-9_']*)?%?/
SYMBOL      = /[A-Z][a-zA-Z0-9_']*/
